<template>
  <div class="q-pa-md">
    <q-table
      class="q-table th.sortable sticky-header-table"
      :columns="columns"
      dark
      :rows="fetchListRatingsFeedback"
      flat
      hide-bottom
      row-key="index"
      :rows-per-page-options="[0]"
      style="max-height: 70vh"
      :table-header-style="{ backgroundColor: '#191919' }"
      :title="coursename"
      virtual-scroll
    >
      <template v-slot:top-right>
        <q-fab flat icon="download" direction="left" label="Download" padding="sm">
          <q-fab-action flat icon="fas fa-file-pdf" @click="downloadPDFReport()">
            <q-tooltip anchor="top middle" self="bottom middle">Download PDF</q-tooltip>
          </q-fab-action>
          <q-fab-action flat icon="fas fa-file-csv" @click="downloadCSVReport()">
            <q-tooltip anchor="top middle" self="bottom middle">Download CSV</q-tooltip>
          </q-fab-action>
        </q-fab>
      </template>
    </q-table>
    <p class="ase-black-light q-pa-lg text-center text-h5 text-weight-bold" v-if="!isLoading && !fetchListRatingsFeedback.length">
      NO DATA
    </p>
    <div class="text-center" v-if="Object.keys(feedbackPaginationKeyForward).length > 0">
      <q-btn
        :class="{ disable_class: Object.keys(feedbackPaginationKeyForward).length === 0 }"
        :disable="Object.keys(feedbackPaginationKeyForward).length === 0"
        icon="keyboard_arrow_right"
        label="Load More"
        style="border: 2px solid white; margin: 7px 0px 7px 0px"
        @click="loadMoreFeedbackRating(feedbackPaginationKeyForward)"
      />
    </div>

    <vue3-html2pdf
      :filename="`Feedback - ${coursename} - Report - ${readableDate_Now}`"
      :pdf-quality="2"
      ref="html2Pdf"
      :preview-modal="false"
      :enable-download="true"
      :manual-pagination="true"
      pdf-format="a4"
      :html-to-pdf-options="{ margin: [4, 0], filename: `Feedback - ${coursename} - Report - ${readableDate_Now}` }"
    >
      <template v-slot:pdf-content>
        <div class="q-my-xl q-py-xl html2pdf__page-break">
          <hr />
          <h3 class="ase-roboto text-center text-weight-medium">User Information</h3>
          <hr />
          <h4 class="text-center" style="margin-top: 200px">{{ fetchUserInfo.email }}</h4>
          <h5 class="text-center">Role: {{ fetchUserInfo.role }}</h5>
          <h6 class="text-center">
            Report generated by {{ fetchUserInfo.firstName }} {{ fetchUserInfo.lastName }} on
            <br />
            <span>{{ readableDate_Now }}</span>
          </h6>
        </div>
        <div class="q-pa-md" style="border: 2px solid gray">
          <q-table
            :columns="columns"
            :rows="fetchListRatingsFeedback"
            hide-bottom
            row-key="index"
            :title="coursename"
            :table-header-style="{ backgroundColor: 'gray', color: 'white', fontWeight: 'bold' }"
            :pagination="{ rowsPerPage: 50005 }"
          />
        </div>
      </template>
    </vue3-html2pdf>
  </div>
</template>

<script setup>
import { Notify } from 'quasar'
import { useCourseStore, useLoginStore } from 'src/stores'
import { downloadCSV, readableDateNow, urlSafeBase64Decode } from 'src/utils/reuseFunctions'
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import Vue3Html2pdf from 'vue3-html2pdf'

const props = defineProps(['coursename'])

const readableDate_Now = ref(readableDateNow())
// const pagination = ref({ sortBy: 'desc', descending: false, page: 1, rowsPerPage: 8 })
const columns = ref([
  { name: 'Email', label: 'Email', field: 'Email', sortable: true, align: 'left' },
  { name: 'Rating', label: 'Rating', field: 'Rating', sortable: true, align: 'left' },
  { name: 'Progress', label: 'Progress', field: 'Progress', sortable: true, align: 'left' },
  { name: 'Created On', label: 'Created On', field: 'Created On', sortable: true, align: 'left' },
  { name: 'Description', label: 'Description', field: 'Description', sortable: true, align: 'left' }
])
const html2Pdf = ref(null)
const courseStore = useCourseStore()
const loginStore = useLoginStore()
const route = useRoute()

const isLoading = computed(() => courseStore.loading)
const fetchListRatingsFeedback = computed(() => (courseStore.rating_feedback.length > 0 ? [...new Set(courseStore.rating_feedback)] : []))
const feedbackPaginationKeyForward = computed(() => courseStore.paginationKeyRating)
const fetchUserInfo = computed(() => loginStore.fetchUserInfo)

onMounted(() => {
  courseStore.fetchRatingAndFeedback({
    pagination: {
      event_id: urlSafeBase64Decode(route.params.courseId)
    },
    reset: true
  })
})

function loadMoreFeedbackRating(pagination) {
  const data = {
    pagination: { event_id: urlSafeBase64Decode(route.params.courseId) },
    reset: false
  }
  if (Object.keys(pagination).length) {
    data.pagination.pagination = pagination
  }
  courseStore.fetchRatingAndFeedback(data)
}
function downloadPDFReport() {
  html2Pdf.value.generatePdf()
}
async function downloadCSVReport() {
  const status = downloadCSV(
    columns.value,
    fetchListRatingsFeedback.value,
    `Feedback - ${props.coursename} - Report - ${readableDateNow()}`
  )

  if (!status) {
    Notify.create({
      message: 'Error while exporting',
      color: 'negative',
      position: 'top',
      timeout: 2000
    })
  }
}
</script>
<style lang="sass">
.sticky-header-table
  .q-table__top,
  .q-table__bottom,
  thead tr:first-child th,
  thead tr th
    position: sticky
    z-index: 1
  thead tr:first-child th
    top: 0
</style>
